<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Export Data User</title>
    <style>
        body { font-family: sans-serif; font-size: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        h2 { text-align: center; color: #333; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8px; color: #777; }
    </style>
</head>
<body>
    <h2>Data User Export</h2>
    <p>Export Date: {{ date('Y-m-d H:i:s') }}</p>
    
    @if(!empty($grouped_by))
        <p><strong>Grouped By:</strong> {{ implode(', ', $grouped_by) }}</p>
    @endif

    <table>
        <thead>
            <tr>
                <th>User Name</th>
                <th>Name</th>
                <th>Level User</th>
                <th>Email Address</th>
                <th>Department</th>
                <th>Group</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td>{{ $user->user_name }}</td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->level_user }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->department }}</td>
                <td>{{ $user->group }}</td>
                <td>{{ $user->status }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Kanmo Contact Center System
    </div>
</body>
</html>
